
package mypackage;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertEuroToDH", targetNamespace = "http://ws/", className = "mypackage.ConvertEuroToDH")
    @ResponseWrapper(localName = "convertEuroToDHResponse", targetNamespace = "http://ws/", className = "mypackage.ConvertEuroToDHResponse")
    @Action(input = "http://ws/BanqueWS/convertEuroToDHRequest", output = "http://ws/BanqueWS/convertEuroToDHResponse")
    public double convertEuroToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns mypackage.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "mypackage.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "mypackage.GetCompteResponse")
    @Action(input = "http://ws/BanqueWS/getCompteRequest", output = "http://ws/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeCompte", targetNamespace = "http://ws/", className = "mypackage.GetListeCompte")
    @ResponseWrapper(localName = "getListeCompteResponse", targetNamespace = "http://ws/", className = "mypackage.GetListeCompteResponse")
    @Action(input = "http://ws/BanqueWS/getListeCompteRequest", output = "http://ws/BanqueWS/getListeCompteResponse")
    public List<Compte> getListeCompte();

}
